# Generated by Django 5.0.4 on 2024-05-04 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='description',
            new_name='details',
        ),
    ]
