# Generated by Django 5.0.4 on 2024-05-04 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='service',
            new_name='service_name',
        ),
    ]
