# Generated by Django 5.0.4 on 2024-05-04 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_rename_service_reservation_service_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='service_name',
            new_name='service',
        ),
    ]
