# Generated by Django 5.0.4 on 2024-05-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_reservation_first_name_reservation_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='first_name',
            field=models.CharField(default='First Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='last_name',
            field=models.CharField(default='Last Name', max_length=255),
        ),
    ]
