# Generated by Django 5.0.4 on 2024-05-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0015_delete_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
