# Generated by Django 5.0.4 on 2024-05-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0016_alter_reservation_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='details',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
