# Generated by Django 5.0.4 on 2024-05-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0017_services_price_alter_services_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
