# Generated by Django 5.0.4 on 2024-05-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0019_alter_reservation_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
