# Generated by Django 5.0.4 on 2024-05-19 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0022_transaction_payment_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payment_completed',
        ),
    ]
